env = "dev"
rg = "rg-dev-tf-azure-sample"
virtualnet = "dev-vnet-tf-azure-sample"
vnet-subnet = "dev-subnet-aks-tf-azure-sample"
aks  = "dev-aks-tf-azure-sample"
aks_dns_prefix  = "dev-dns-aks-tf-azure-sample"
storage = "dev-sgtfazuresample"